[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "./src/arch/aarch64/aarch64-unknown-none-softfloat.json"

[target.'cfg(target_os = "none")']
runner = "qemu-system-aarch64 -machine virt -m 1G -cpu cortex-a53 -nographic -kernel"
