[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "aarch64-unknown-none-softfloat.json"
# target = "aarch64-unknown-none-softfloat"

[target.'cfg(target_os = "none")']
runner = "qemu-system-aarch64 -machine virt -m 1024M -cpu cortex-a53 -nographic -kernel"
